= Home

This is the wiki describing the components from which the Telemetry system is constructed.

There are 3 distinct parts to the Telemetry system.

.Telemetry System Components
* Data Collector
* Data Transmission
* Data Reception

.High level data flow through the system
[mermaid]
----
graph LR

    Collector --> Transmission
    Transmission --> Reception
----

== Data Collector

The data collector collects and converts the sensor data to a string format.
This data is then either logged to the microSD card and/or send to the Data Transmission


== Data Transmission
The Data transmission unit takes the ascii string of data and converts it into structs where it takes the average of the values over a second.
These average values are then converted into JSON and transfered over wifi through a mifi unit to the server where the Data reception occurs


== Data Reception

The data receiver takes the data in json form and constructs a database insertion query from it and inserts the data into the database
Next to this program there is a mysql database and a graphana dashboard for storage and visualisation 

== Full architecture

The full architecture of the Telemetry system is shown below. 
This shows the data paths and flow through the system

.Telemetry System Full Architecture
[mermaid]
----

graph LR
    
    subgraph Collection
        ADXL[ADXL345] --> P1[Processing]
        Spc[Spectronik controller]--> P2[Processing]

        cb[CanCallback] --> Can_Throttle_Processing
        cb[CanCallback] --> Can_Telemetry_Processing
        cb[CanCallback] --> Can_Motor_Processing

        Can_Throttle_Processing  --> Collect
        Can_Telemetry_Processing --> Collect
        Can_Motor_Processing     --> Collect

        P1 --> Collect[Collector]
        P2 --> Collect


    end
    Collect --> Openlog
    Openlog --> microSD

    subgraph Transmission
        Collect --> ESP32
        ESP32 --> MQTT
    end


    subgraph Reception
        MQTT --> Server
        Server --> Database
        Database --> Dashboard
    end
----

== CI/CD
The current repository has a CI/CD setup which test if the pushed code for STM32 compiles against the targeted board. 
this is done using the cmake file in the CompleteSystem directory.
The docker file for the container which tests the compilation is available in the docker_ci folder in the repository.
This Dockerfile can be turned into a container with the command `docker build -t {Container_name}`.

The CI/CD is configured using the `.gitlab-ci.yml` file in the root of the repository.
This also has a old and currently non functional formatting checker but it is commented out.
Gitlab is also used as the images Docker registry.

[source,yml]
----
stm:build:
  image: registry.gitlab.com/hydromotive/2425-acquistionmodule-dev/arm-none-eabi-gcc:1.0.0 # <1>
  #needs: ["stm:fmt"]
  stage: build
  before_script:
    - apt update && apt -y install make autoconf cmake
  script:
    - mkdir -p CompleteSystem/build
    - cd CompleteSystem/build
    - CC="arm-none-eabi-gcc" CXX="arm-none-eabi-g++" cmake ..
    - cmake --build . --config Release -j 4
  artifacts:
    paths:
      - CompleteSystem/build/CompleteSystem.elf # <2>
----
<1> Image used to compile the project
<2> Binary file build by the image which is saved for a limited time on gitlab
