---
title: "motor telemery ID: Can TX +0"
---
packet-beta

+16: "Control value"
+2: "control mode"
+3: "motor mode"
+1: "sw enable"
+2: "motor state"
+16: "motor torque"
+16: "motor rpm"
+8: "motor temp"
